before_script:
  - brew list
  - brew info libpng
  - brew info freetype
  - brew remove libpng jpeg libxml2 libtiff libtool
  - brew install --universal freetype jpeg libtiff little-cms2 sane-backends libgphoto2 libgsm
language: objective-c
compiler:
  - clang
# Change this to your needs
script:
  - ./configure --without-x
  - make -j4 2>&1 | grep -A100 -B100 -e 'error:' -e 'gcc'
  - make test -k 2>&1 | grep -A100 -B100 -e 'Test failed:' -e 'the last test' -e 'runtest'
