1 cdecl PacketAllocatePacket()
2 stub PacketCloseAdapter
3 cdecl PacketFreePacket(ptr)
4 stub PacketGetAdapterNames
5 stub PacketGetAirPcapHandle
6 stub PacketGetDriverVersion
7 stub PacketGetNetInfoEx
8 stub PacketGetNetType
9 stub PacketGetReadEvent
10 stub PacketGetStats
11 stub PacketGetStatsEx
12 stub PacketGetVersion
13 stub PacketInitPacket
14 stub PacketIsDumpEnded
15 stub PacketLibraryVersion
16 stub PacketOpenAdapter
17 stub PacketReceivePacket
18 stub PacketRequest
19 stub PacketSendPacket
20 stub PacketSendPackets
21 stub PacketSetBpf
22 stub PacketSetBuff
23 stub PacketSetDumpLimits
24 stub PacketSetDumpName
25 stub PacketSetHwFilter
26 stub PacketSetLoopbackBehavior
27 stub PacketSetMinToCopy
28 stub PacketSetMode
29 stub PacketSetNumWrites
30 stub PacketSetReadTimeout
31 stub PacketSetSnapLen
32 stub PacketStopDriver
